### ISSUE TITLE
Android | App does not start

### ISSUE THREAD

**Issue by patschwork** [enm10k/nocodb-mobile#1] opened 2023-09-03 12:45 UTC
Hi !

Thank you for your effort and making this open-source 🙂

I tried the apk. When launching the app it doesn't come up (maybe crashes immediatly 🤷).
Are there some kind of logs (on the device)?
I've seen, the Flutter Logger was implemented, but as far as I've seen (roughly glimpse), the log are for debugging when in "dev mode" when coding 😂. But maybe I'm wrong....

**Comment by enm10k** [comment] 2023-09-03 12:59
Hello,
I'm sorry to hear that crashes and their causes are not being displayed.

Could you please tell me the version of NocoDB you are using?
I have also experienced issues that the app fails to start due to non-backward compatible changes in the API, especially after upgrading the NocoDB version during development.

If you can provide the information, I will look into it.

**Comment by patschwork** [comment] 2023-09-03 13:10
The app doesn't show up (crashes before there is any dialog to enter the server URL etc.).

Therefore I guess, it is not depending on the NocoDB server version...🤷
Or does the app trying to search for the API on the network?

In any case: NocoDB 0.108.1

**Comment by enm10k** [comment] 2023-09-03 13:19
> The app doesn't show up (crashes before there is any dialog to enter the server URL etc.).
> ...
> Or does the app trying to search for the API on the network?

If the app is crashing before you enter your NocoDB URL, it doesn't seem like the NocoDB version is the cause.
And at this point, there is no way for me to debug the problem.

Possible actions to take include:

- Building the program from source on your Android device to reproduce the problem.
- Creating an APK with a solution to collect crash information and having you try it again.

Also, since the apk is not being distributed through the Play Store, there's a possibility that the OS security features may be preventing it from running.
I would like you to check that as well.

**Comment by UnicornyRainbow** [comment] 2023-09-11 13:12
Hey, just wanted to tell you i have the same problem, it crashes when i try to start it. If I come around to debug it a bit I will share my results, but i dont really have experience with flutter, so i will see what i can do...

**Comment by patschwork** [comment] 2023-09-11 15:30
> Hey, just wanted to tell you i have the same problem, it crashes when i try to start it. If I come around to debug it a bit I will share my results, but i dont really have experience with flutter, so i will see what i can do...

Hey, same here. I installed everything for developing flutter but haven't had spare time to got into it.... 
Thanks for your help 🙂

**Comment by enm10k** [comment] 2023-09-12 15:30
Thank you for your interest in this project.
I will also investigate a bit more about the build settings and the generated apk.

Additionally, once you have set up the Android development environment, you might be able to find some useful information from the Android OS logs using adb.

**Comment by enm10k** [comment] 2023-09-16 14:55
@patschwork @UnicornyRainbow 

I cloned the project and the issue reproduced.
I fixed it in the following commit.
https://github.com/enm10k/nocodb-mobile/commit/2fb74bd45f57901344f8f4eb2814c68638bb3469

Before making this project public, I mistakenly modified the .gitignore, causing the MainActivity.kt file to be deleted from git, which resulted in the Android app not being able to launch.

**Comment by UnicornyRainbow** [comment] 2023-09-17 09:12
I can confirm that it launches, if I find any other bugs I let you know. Thank you!

**Comment by enm10k** [comment] 2023-10-12 12:30
I will close this issue.
Please reopen it if you still have any problems.

**Closed as completed by enm10k** 2023-10-12 12:30 UTC
